### ISSUE TITLE
Kick off

### ISSUE THREAD

**Issue by f3l1x** [contributte/event-dispatcher-extra#1]
#Move logic from:

- https://github.com/contributte/event-application-bridge
- https://github.com/contributte/event-security-bridge
- https://github.com/contributte/event-bridges

Info:
- namespace = Contributte\Events\Extra
- composer = contributte/event-dispatcher-extra

After that:
- setup new composer package
- setup CI
- archive packages / abbandon packagist

**Comment by mabar** [comment]
@f3l1x Tag current master as 0.1, archive old packages and you can close it

**Comment by f3l1x** [comment]
Done. Thanks.
