### ISSUE TITLE
Symfony\EventDispatcher v5.0.0

### ISSUE THREAD

**Issue by solcik** [contributte/event-dispatcher-extra#30]
There is a compatibility problem with EventDispatcher v5.0.0

https://github.com/symfony/symfony/blob/master/UPGRADE-5.0.md#eventdispatcher

> The Event class has been removed, use Symfony\Contracts\EventDispatcher\Event instead

So every usage of

```php
use Symfony\Component\EventDispatcher\Event; 
```

should be changed to 

```php
use Symfony\Contracts\EventDispatcher\Event;
```

The "old" Event was deprecated since SF 4.3

```
@deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead
```

Should I prepare PR for this? Should I raise composer dependency to SF 4.4?

**Comment by mabar** [comment]
Should be fixed by fc73be8
Composer didn't allow me to install SF 5 and I didn't notice
Thanks for warning
