### ISSUE TITLE
Dependence on a specific version of nette/application

### ISSUE THREAD

**Issue by jaroslavlibal** [contributte/event-dispatcher-extra#35]
The library depends on a specific version of the nette/application, but this dependence is granted only as dev-requirement.

At least the [PresenterShutdownEvent](https://github.com/contributte/event-dispatcher-extra/blob/master/src/Event/Application/PresenterShutdownEvent.php#L18) and [ResponseEvent](https://github.com/contributte/event-dispatcher-extra/blob/master/src/Event/Application/ResponseEvent.php#L18) depends on the IResponse interface which is deprecated since nette/application 3.1.

Maybe the Nette 3.1+ compatible release should be released and the nette/application dependence should be moved to the require section?

**Comment by f3l1x** [comment]
Deps are optional because it's up to you which event/subscriber you want. 

I agree that we can release a new version nette 3.1 compatible. Will you prepare a PR?

**Comment by f3l1x** [comment]
Resolve https://github.com/contributte/event-dispatcher-extra/releases/tag/v0.9.0
