### ISSUE TITLE
LogicException You use Latte 3 together with the code designed for Latte 2

### ISSUE THREAD

**Issue by petrparolek** [contributte/event-dispatcher-extra#40]
Version: master

### Bug Description

```
LogicException
You use Latte 3 together with the code designed for Latte 2 (in /var/www/html/temp/cache/nette.configurator/Container_ab1482d62c.php on 3112)
```

### Steps To Reproduce

Register DI extension `Contributte\Events\Extra\DI\EventLatteBridgeExtension`

### Expected Behavior

no exception

### Possible Solution

fix incompatible code in https://github.com/contributte/event-dispatcher-extra/blob/2e719464deee6d9be374b0a3ea0d0f43fb90c36e/src/DI/EventLatteBridgeExtension.php#L37-L43

**Comment by sasule** [comment]
Quick and dirty workaround can be to switch off latte if you don't need those events.

**Comment by petrparolek** [comment]
ping @f3l1x

**Comment by juklicek** [comment]
@f3l1x - any chance you will fix the issue? :) Thx

**Comment by f3l1x** [comment]
I will do it this week.

**Comment by f3l1x** [comment]
Solved. It took more then one week ;-)
